const questions = [
  {
    id: 1,
    questions: "5 + 4 = ?",
    questionType: "calculation",
    correctAns: "9",
    option1: "5",
    option2: "4",
    wrongAns: false,
    rightAns: false,
    notAttemptQus: true,
    activeQus: false,
    attempts: 6,
    flag: false,
    flagId: "",
  },
  {
    id: 2,
    questions: "Complete the pattern",
    questionType: "pattern",
    correctAns: "346348",
    wrongAns: false,
    rightAns: false,
    notAttemptQus: true,
    activeQus: false,
    attempts: 6,
    flag: false,
    flagId: "",
  },
  {
    id: 3,
    questions: "Sort the element in correct order",
    questionType: "sorting",
    correctAns: "javaScriptHtmlCss",
    wrongAns: false,
    rightAns: false,
    notAttemptQus: true,
    activeQus: false,
    attempts: 6,
    flag: false,
    flagId: "",
  },
  {
    id: 4,
    questions: "Sort the element in correct order",
    questionType: "inputSorting",
    correctAns: "1234",
    wrongAns: false,
    rightAns: false,
    notAttemptQus: true,
    activeQus: false,
    attempts: 6,
    flag: false,
    flagId: "",
  },
  {
    id: 5,
    questions: "Choose your write option",
    questionType: "redo",
    correctAns: "correct",
    wrongAns: false,
    rightAns: false,
    notAttemptQus: true,
    activeQus: false,
    attempts: 6,
    flag: false,
    flagId: "",
  },
  {
    id: 6,
    questions: "Select the numbers that are divisible by 2",
    questionType: "checkbox",
    correctAns: "secondforth",
    wrongAns: false,
    rightAns: false,
    notAttemptQus: true,
    activeQus: false,
    attempts: 6,
    flag: false,
    flagId: "",
  },
];

export { questions };
